# Each new term in the Fibonacci sequence is generated by adding the previous two #terms. By starting with 1 and 2, the first 10 terms will be:
  
#  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence whose values do not exceed four #million, find the sum of the even-valued terms.



fabonacci <- function(x){
  if(x == 0 | x == 1){
    return(1)
  }else{
    return(fabonacci(x-1)+fabonacci(x-2))
  }
}

x <- 1
f <- list()
while(fabonacci(x) < 4000000){
  if(fabonacci(x) %% 2 == 0){
  f[[x]] <- fabonacci(x)   # very very important
  }
  x <- x+1
}
# list do not have function sum.
result <- sum(unlist(f))
