#The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
  
#  1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

#Let us list the factors of the first seven triangle numbers:
  
1: 1
3: 1,3
6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28

#We can see that 28 is the first triangle number to have over five divisors.

#What is the value of the first triangle number to have over five hundred divisors?
  


#method one
div_tri_num <- function(count){
  n <- 1
  c <- 2
  while(c <= count){
    c <- 2
    n <- n + 1
    m <- n*(n+1)/2
    half <- as.integer(sqrt(m))
    for(i in 2:half){
      if(m %% i == 0){
        c <- c + 2
      }
    }
  }
  return(c('n'= n, 'm' = m))
}

timestart <- Sys.time()
div_tri_num(500)
timestop <- Sys.time()
(timecost <- timestop - timestart)  #24s

#method two
divisors_num <- function(n){
  c = 2
  m <- as.integer(sqrt(n))
  if(m >= 2){
    for(i in 2:m){
      if(n %% i == 0){
        c <- c + 2
      }
    }
  }
  if(m == sqrt(n)){
    return(c-1)
  }else{
    return(c)
  }
}

div_tri_num <- function(count){
  n <- 1
  d <- 1
  while(d <= count){
    n <- n + 1
    if(n %% 2 ==0){
      d <- divisors_num(n/2) * divisors_num(n+1)
    }else{
      d <- divisors_num(n) * divisors_num((n+1)/2)
    }
  }
  return(c('n' = n, 'm' = n*(n+1)/2))
}

timestart <- Sys.time()
div_tri_num(500)
timestop <- Sys.time()
(timecost <- timestop - timestart)  #0.8s