#Triangular, pentagonal, and hexagonal
#Problem 45

#Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
#  Triangle 	  	Tn=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
#Pentagonal 	  	Pn=n(3n−1)/2 	  	1, 5, 12, 22, 35, ...
# Hexagonal 	  	Hn=n(2n−1) 	  	1, 6, 15, 28, 45, ...

#It can be verified that T285 = P165 = H143 = 40755.

#Find the next triangle number that is also pentagonal and hexagonal.


n = 286
while(TRUE){
  T <- n*(n+1)/2
  if((1+(1+24*T)**0.5)%%6 == 0 & (1+(1+8*T)**0.5)%%4 == 0){
    print(T)
    break
  }
  n <- n+1
}